version: "3"

services:
  ldap:
    image: osixia/openldap:1.4.0
    hostname: ldap.chalmers.it
    environment:
      #admin username: cn=admin,dc=chalmers,dc=it
      #admin password: password

      LDAP_ORGANISATION: "digIT"
      LDAP_DOMAIN: "chalmers.it"
      LDAP_BASE_DN: "dc=chalmers,dc=it"
      LDAP_ADMIN_PASSWORD: "password"
      LDAP_SEED_INTERNAL_LDIF_PATH: /ldif
      LDAP_SEED_INTERNAL_SCHEMA_PATH: /schemas
      LDAP_TLS_VERIFY_CLIENT: try
    volumes:
      - ./mock/ldif:/ldif
      - ./mock/schemas:/schemas
    ports:
      - 389:389
      - 636:636

  ldap-admin:
    build:
      context: ./
      dockerfile: ldap-admin.Dockerfile
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:{'ldap':[{'login':[{'auth_type':'session'},{'bind_id':'cn=admin,dc=chalmers,dc=it'}]}]}"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - ldap
    ports:
      - 9000:80
