version: "3"
networks:
    gamma:

services:
    gamma-db:
        image: postgres:10
        environment:
            POSTGRES_USER: user
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: password
        networks:
            - gamma

    gamma-frontend:
        image: cthit/gamma-frontend:development
        environment:
            HTTP_PROXY: http://gamma-backend:8081
        ports:
            - 3000:3000
        depends_on:
            - gamma-backend
        networks:
            - gamma

    gamma-backend:
        image: cthit/gamma-backend:development
        environment:
            # Default admin user name = admin
            # Default admin password  = password

            DB_USER: user
            DB_PASSWORD: password
            DB_HOST: gamma-db
            DB_PORT: 5432
            DB_NAME: postgres

            REDIS_HOST: redis
            REDIS_PASSWORD: ""

            SERVER_PORT: 8081
            FRONTEND_REDIRECT_URI: http://localhost:3000/login
            SUCCESSFUL_LOGIN: http://localhost:3000
            CORS_ALLOWED_ORIGIN: http://localhost:3000
            COOKIE_DOMAIN: localhost
            PRODUCTION: "false"
            IS_MOCKING_CLIENT: "true"
            DEFAULT_REDIRECT_URI: http://localhost:3001/callback
        networks:
            - gamma
        depends_on:
            - gamma-db
            - redis
        ports:
            - 8081:8081

    redis:
        image: redis:5.0
        networks:
            - gamma
